Models/OrderDetail.cs
using System;
using System.Collections.Generic;

namespace FinalProjectPRN221.Models
{
    public partial class OrderDetail
    {
        public int OrderDetailId { get; set; }
        public int? OrderId { get; set; }
        public int? ProductId { get; set; }
        public int? Quantity { get; set; }
        public int? UnitPrice { get; set; }

        public virtual Order? Order { get; set; }
        public virtual Product? Product { get; set; }
    }
}

Pages/Products/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using FinalProjectPRN221.Models;

namespace FinalProjectPRN221.Pages.Products
{
    public class CreateModel : PageModel
    {
        private readonly Project_PRN221Context _context;

        public CreateModel(Project_PRN221Context context)
        {
            _context = context;
        }
        public SelectList CategoryOptions { get; set; }
        public SelectList SupplierOptions { get; set; }
        public IActionResult OnGet()
        {
            if (HttpContext.Request.Cookies["LoginCookie"] == null)
            {
                // Chuyển hướng đến trang đăng nhập
                return RedirectToPage("/Account/Login");
            }
            else
            {
                var categories = _context.Categories.ToList();
                var suppliers = _context.Suppliers.ToList();

                // Tạo danh sách lựa chọn từ danh sách danh mục
                CategoryOptions = new SelectList(categories, nameof(Category.CategoryId), nameof(Category.CategoryName));
                SupplierOptions = new SelectList(suppliers, nameof(Supplier.SupplierId), nameof(Supplier.SupplierName));

                // Continue processing for the logged-in user
            }

            // You might return a page or perform additional actions here
            return Page();
        }

        [BindProperty]
        public Product Product { get; set; } = default!;
        public Category Category { get; set; } = new Category();
        public Supplier Supplier { get; set; } = new Supplier();


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (_context.Products == null || Product == null)
            {
                return Page();
            }

            _context.Products.Add(Product);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }

        
    }
}

Pages/Products/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FinalProjectPRN221.Models;

namespace FinalProjectPRN221.Pages.Products
{
    public class DetailsModel : PageModel
    {
        private readonly Project_PRN221Context _context;

        public DetailsModel(Project_PRN221Context context)
        {
            _context = context;
        }

      public Product Product { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (HttpContext.Request.Cookies["LoginCookie"] == null)
            {
                // Chuyển hướng đến trang đăng nhập
                return RedirectToPage("/Account/Login");
            }
            else
            {
                if (id == null || _context.Products == null)
                {
                    return NotFound();
                }

                var product = await _context.Products.Include(p => p.Category)
                    .Include(p => p.Supplier)
                    .FirstOrDefaultAsync(m => m.ProductId == id);
                if (product == null)
                {
                    return NotFound();
                }
                else
                {
                    Product = product;
                }
                return Page();
            }
        }
    }
}

Pages/Products/Index.cshtml.cs
using FinalProjectPRN221.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Security.Claims;

namespace FinalProjectPRN221.Pages.Products
{
    public class IndexModel : PageModel
    {
        private readonly Project_PRN221Context _context;
        private readonly IConfiguration Configuration;

        public IndexModel(Project_PRN221Context context, IConfiguration configuration)
        {
            _context = context;
            Configuration = configuration;
        }
        public List<Product> ListOfProduct = new List<Product>();
        public List<Category> ListOfCategory = new List<Category>();
        public List<Supplier> ListOfSuppliers = new List<Supplier>();
        public string NameSort { get; set; }
        public string DateSort { get; set; }
        public string CurrentFilter { get; set; }
        public string CurrentSort { get; set; }
        public string IdSort { get; set; }
        public PaginatedList<Product> Products { get; set; }
        public async Task<IActionResult> OnGetAsync(string sortOrder, string currentFilter, string searchString, int categoryId, int supplierId, int? pageIndex)
        {
            if (HttpContext.Request.Cookies["LoginCookie"] == null)
            {
                // Chuyển hướng đến trang đăng nhập
                return RedirectToPage("/Account/Login");
            }
            else
            {
                CurrentSort = sortOrder;
                IdSort = string.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
                DateSort = sortOrder == "Date" ? "date_desc" : "Date";
                NameSort = sortOrder == "Name" ? "name_desc" : "Name";
                ListOfCategory = _context.Categories.ToList();
                ListOfSuppliers = _context.Suppliers.ToList();

                IQueryable<Product> query = _context.Products
                    .Include(x => x.Category)
                    .Include(x => x.Supplier);

                if (categoryId != 0)
                {
                    query = query.Where(p => p.CategoryId == categoryId);
                }

                if (supplierId != 0)
                {
                    query = query.Where(p => p.SupplierId == supplierId);
                }
                if (searchString != null)
                {
                    pageIndex = 1;
                }
                else
                {
                    searchString = currentFilter;
                }
                CurrentFilter = searchString;
                if (!string.IsNullOrEmpty(searchString))
                {
                    query = query.Where(s => s.ProductName.Contains(searchString));
                }
                switch (sortOrder)
                {
                    case "name_desc":
                        query = query.OrderByDescending(s => s.ProductName);
                        break;
                    case "Date":
                        query = query.OrderBy(s => s.ExpirationDate);
                        break;
                    case "date_desc":
                        query = query.OrderByDescending(s => s.ExpirationDate);
                        break;
                    case "Name": // Sorting by ID
                        query = query.OrderBy(s => s.ProductName);
                        break;
                    case "id_desc": // Sorting by ID in descending order
                        query = query.OrderByDescending(s => s.ProductId);
                        break;
                    default:
                        query = query.OrderBy(s => s.ProductId);
                        break;
                }
                ListOfProduct = await query.ToListAsync();
                if (ListOfProduct != null)
                {
                    var pageSize = Configuration.GetValue("PageSize", 5);
                    Products = await PaginatedList<Product>.CreateAsync(query.AsNoTracking(), pageIndex ?? 1, pageSize);
                }
                return Page();
            }
            
        }
        public IActionResult OnGetDelete(int productId)
        {
            var userRoleId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;

            if (userRoleId == "1")
            {
                var product = _context.Products.Find(productId);
                if (product != null)
                {
                    var orderDetails = _context.OrderDetails
                        .Where(x => x.ProductId == product.ProductId).ToList();

                    foreach (var orderDetail in orderDetails)
                    {
                        _context.OrderDetails.Remove(orderDetail);
                    }

                    _context.Products.Remove(product);
                    _context.SaveChanges();

                    // Redirect back to the index page
                    return RedirectToPage("/Products/Index");
                }
                else
                {
                    TempData["ErrorMessage"] = "Không tìm thấy sản phẩm này!!!";
                    return RedirectToPage("/Products/Index");
                }
            }
            else
            {
                // Return a message indicating insufficient permissions
                TempData["ErrorMessage"] = "Bạn không có quyền hạn này.";
                return RedirectToPage("/Products/Index");
            }
        }
        [BindProperty]
        public int? OrderId { get; set; }

        public async Task<IActionResult> OnPostAddToOrderAsync(int productId)
        {
            var currentUserIdClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);

            if (currentUserIdClaim != null && int.TryParse(currentUserIdClaim.Value, out int currentUserId))
            {
                var product = await _context.Products.FindAsync(productId);

                if (product != null)
                {
                    var order = await _context.Orders
                        .Include(o => o.OrderDetails)
                        .Where(o => o.UserId == currentUserId && o.IsPaid == "0")
                        .FirstOrDefaultAsync();

                    if (order == null)
                    {
                        order = new Models.Order
                        {
                            UserId = currentUserId,
                            OrderDate = DateTime.Now,
                            OrderDetails = new List<OrderDetail>()
                        };

                        _context.Orders.Add(order);

                        await _context.SaveChangesAsync();

                        OrderId = order.OrderId;
                    }
                    else
                    {
                        OrderId = order.OrderId;
                    }

                    var orderItem = new OrderDetail
                    {
                        ProductId = product.ProductId,
                        Quantity = 1,
                        UnitPrice = product.Price ?? 0,
                    };

                    order.OrderDetails.Add(orderItem);

                    await _context.SaveChangesAsync();
                }

                return RedirectToPage("/Products/OrderDetails", new { orderId = OrderId });
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
    }
}

Pages/Products/OrderDetails.cshtml.cs
using FinalProjectPRN221.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace FinalProjectPRN221.Pages.Products
{
    public class OrderDetailsModel : PageModel
    {
        private readonly Project_PRN221Context _context;

        public OrderDetailsModel(Project_PRN221Context context)
        {
            _context = context;
        }

        [BindProperty(SupportsGet = true)]
        public int? OrderId { get; set; }

        public List<OrderDetail> OrderItems { get; set; }

        public string Message { get; set; }

        public IActionResult OnGet()
        {
            if (HttpContext.Request.Cookies["LoginCookie"] == null)
            {
                // Chuyển hướng đến trang đăng nhập
                return RedirectToPage("/Account/Login");
            }
            else
            {
                LoadOrderDetails();
                return Page();
            }
        }

        private void LoadOrderDetails()
        {
            var groupedOrderItems = _context.OrderDetails
                .Where(oi => oi.OrderId == OrderId && oi.Order != null && oi.Order.IsPaid == "0")
                .GroupBy(oi => oi.ProductId)
                .Select(group => new OrderDetail
                {
                    ProductId = group.Key.Value,
                    Quantity = group.Sum(item => item.Quantity),
                    UnitPrice = group.First().UnitPrice,
                    Product = group.First().Product
                })
                .ToList();

            OrderItems = groupedOrderItems;
        }
        public IActionResult OnPostDeleteProduct(int productId)
        {
            var orderDetailsToDelete = _context.OrderDetails.Where(od => od.ProductId == productId).ToList();

            if (orderDetailsToDelete != null)
            {
                _context.OrderDetails.RemoveRange(orderDetailsToDelete);
                _context.SaveChanges();

                // Lấy orderId từ OrderItems (hoặc từ đâu đó)
                int? orderId = orderDetailsToDelete.FirstOrDefault()?.OrderId;

                TempData["Message"] = "Product deleted successfully!";
                // Chuyển hướng về trang OrderDetails với orderId
                return RedirectToPage("/Products/OrderDetails", new { orderId });
            }

            return Page();
        }

        public IActionResult OnPostUpdateQuantity(int productId, int newQuantity, int orderId)
        {
            var orderDetail = _context.OrderDetails
                .Include(od => od.Order)
                .FirstOrDefault(od => od.ProductId == productId && od.OrderId == orderId);

            if (orderDetail != null && orderDetail.Order != null)
            {
                // Lưu giá trị cũ của Quantity
                int? oldQuantity = orderDetail.Quantity;

                // Cập nhật Quantity mới
                orderDetail.Quantity = newQuantity;

                // Kiểm tra xem Order có tồn tại không
                if (orderDetail.Order != null)
                {
                    UpdateTotalAmount(orderId);
                }

                TempData["Message"] = "Quantity updated successfully!";
            }

            return RedirectToPage("/Products/OrderDetails", new { orderId });
        }

        public IActionResult OnPostProcessPayment(int orderId)
        {
            var order = _context.Orders
                .Include(o => o.OrderDetails)
                .FirstOrDefault(o => o.OrderId == orderId);
            if (order != null)
            {
                // Kiểm tra số lượng sản phẩm còn đủ để trừ hay không
                foreach (var orderDetail in order.OrderDetails)
                {
                    var product = _context.Products.FirstOrDefault(p => p.ProductId == orderDetail.ProductId);

                    if (product != null && product.StockQuantity >= orderDetail.Quantity)
                    {
                        // Trừ đi số lượng sản phẩm từ kho
                        product.StockQuantity -= orderDetail.Quantity;
                    }
                    else
                    {
                        // Xử lý trường hợp không đủ số lượng sản phẩm trong kho
                        // Có thể hiển thị thông báo lỗi và không thực hiện thanh toán
                        TempData["Message"] = $"Not enough quantity in stock for product: {product.ProductName}";
                        return Page();
                    }
                }

                // Đặt trạng thái thanh toán thành "Đã thanh toán"
                order.IsPaid = "1";

                // Cập nhật tổng tiền
                UpdateTotalAmount(orderId);

                TempData["Message"] = "Payment successful!";
                // Chuyển hướng về trang OrderDetails với orderId và hiển thị thông báo
                return RedirectToPage("/Products/OrderDetails", new { orderId });
            }

            return Page();
        }
        private void UpdateTotalAmount(int orderId)
        {
            var orderDetails = _context.OrderDetails.Where(od => od.OrderId == orderId).ToList();

            // Lấy Order theo orderId
            var order = _context.Orders.FirstOrDefault(o => o.OrderId == orderId);

            if (order != null)
            {
                // Cập nhật TotalAmount của Order bằng tổng của (UnitPrice * Quantity)
                order.TotalAmount = orderDetails.Sum(od => od.UnitPrice * od.Quantity);
            }

            _context.SaveChanges();
        }
    }
}

Pages/Products/Index.cshtml
@page
@model FinalProjectPRN221.Pages.Products.IndexModel
@{
}

<h1 style="text-align:center; color:blue">List of Products</h1>
<br />
<h4 style="text-align: center;color:blue">Filter</h4>
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}

<div style="margin: 20px 40px;padding: 20px; width:100%; text-align:center; display:flex">
    <form method="get" style="display:flex; justify-content:center; width:60%">
        <div style="width:30%; margin:auto">
            <label>By Categories</label>
            <select name="categoryId" class="form-control">
                <option value="0">All</option>
                @foreach (var category in Model.ListOfCategory)
                {
                    <option value="@category.CategoryId">@category.CategoryName</option>
                }
            </select>
            <button style="text-align:center" type="submit" class="btn btn-primary">Filter</button>
        </div>
        <div style="width:30%; margin:auto">
            <label>By suppliers</label>
            <select name="supplierId" class="form-control">
                <!-- Thêm trường tìm kiếm cho nhà cung cấp -->
                <option value="0">All Suppliers</option>
                @foreach (var supplier in Model.ListOfSuppliers)
                {
                    <option value="@supplier.SupplierId">@supplier.SupplierName</option>
                }
            </select>
            <button style="text-align:center" type="submit" class="btn btn-primary">Filter</button>
        </div>
    </form>

    <form asp-page="./Index" method="get">
        <div class="form-actions no-color" style="width:30%; margin-left: 120px; margin-top:20px;">
            <p>
                Find by name
                <input type="text" name="SearchString" value="@Model.CurrentFilter"
                       style="border: 1px solid #ccc" />
                <input type="submit" value="Search" class="btn btn-primary" />
            </p>
        </div>
    </form>
</div>
<div style="margin: 20px 20px">
    <a href="/Products/Create">Add new products</a>
    @if (Model.OrderId.HasValue)
    {
        <a class="btn btn-primary" asp-page="/Products/OrderDetails" asp-route-orderId="@Model.OrderId">
            View Order Details
        </a>
    }
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
        <thead style="background-color: #f2f2f2;">
            <tr>
                <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                    <a asp-page="./Index" asp-route-sortOrder="@Model.IdSort"
                       asp-route-currentFilter="@Model.CurrentFilter">
                        @Html.DisplayNameFor(model => model.Products[0].ProductId)
                    </a>
                </th>
                <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                    <a asp-page="./Index" asp-route-sortOrder="@Model.NameSort"
                       asp-route-currentFilter="@Model.CurrentFilter">
                        @Html.DisplayNameFor(model => model.Products[0].ProductName)
                    </a>
                </th>
                <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">Image</th>
                <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">Price</th>
                <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">StockQuantity</th>

                @*<th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">Description</th>*@
                @*                    <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">Category</th>
                <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">Supplier</th>*@
                @*<th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">ManufacturingDate</th>*@
                <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                    <a asp-page="./Index" asp-route-sortOrder="@Model.DateSort"
                       asp-route-currentFilter="@Model.CurrentFilter">
                        @Html.DisplayNameFor(model => model.Products[0].ExpirationDate)
                    </a>
                </th>
                <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Products != null)
            {
                @foreach (var product in Model.Products)
                {
                    <tr style="border: 1px solid #dddddd;">
                        <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">@product.ProductId</td>
                        <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">@product.ProductName</td>
                        <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                            <img src="@product.ImageUrl" alt="Product Image" style="max-width: 100px; max-height: 100px;" />
                        </td>
                        @*<td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">@product.Description</td>*@
                        <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">@product.Price</td>
                        <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                            @product.StockQuantity
                            @if (product.StockQuantity <= 5)
                            {
                                <span style="color: red; font-weight: bold;">(Low stock!)</span>
                            }
                        </td>
                        @*<td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">@product.Category.CategoryName</td>
                <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">@product.Supplier.SupplierName</td>*@
                        @*<td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">@product.ManufacturingDate</td>*@
                        <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">@product.ExpirationDate</td>

                        <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                            <a href="/Products/Edit/@product.ProductId">Edit</a>
                            <a href="/Products/Index?handler=Delete&productId=@product.ProductId">Delete</a>
                            <a href="/Products/Details/@product.ProductId">Detail</a>
                        </td>
                        <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                            <form method="post" asp-page-handler="AddToOrder">
                                <input type="hidden" name="productId" value="@product.ProductId" />
                                <button type="submit" class="btn btn-primary">Add to Order</button>
                            </form>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <a asp-page="./Index">Back to full list</a>

</div>
@{
    var prevDisabled = Model.Products != null && !Model.Products.HasPreviousPage ? "disabled" : "";
    var nextDisabled = Model.Products != null && !Model.Products.HasNextPage ? "disabled" : "";
}

<a asp-page="./Index"
   asp-route-sortOrder="@Model.CurrentSort"
   asp-route-pageIndex="@(Model.Products?.PageIndex - 1 ?? 1)"
   asp-route-currentFilter="@Model.CurrentFilter"
   class="btn btn-primary @prevDisabled">
    Prev
</a>
<a asp-page="./Index"
   asp-route-sortOrder="@Model.CurrentSort"
   asp-route-pageIndex="@(Model.Products?.PageIndex + 1 ?? 1)"
   asp-route-currentFilter="@Model.CurrentFilter"
   class="btn btn-primary @nextDisabled">
    Next
</a>

Pages/Products/OrderDetails.cshtml
@page
@model FinalProjectPRN221.Pages.Products.OrderDetailsModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Order Details</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            padding: 20px;
        }

        h1 {
            color: #333;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        tbody tr:hover {
            background-color: #f5f5f5;
        }

        p {
            color: #777;
            font-style: italic;
            margin-top: 20px;
        }

        a {
            display: inline-block;
            margin-top: 20px;
            color: #007bff;
            text-decoration: none;
            font-weight: bold;
        }
    </style>
    <script>
        function updateQuantity(index, operation) {
            var quantityInput = document.getElementById('quantity_' + index);
            var totalElement = document.getElementById('total_' + index);
            var unitPriceElement = document.getElementById('unitPrice_' + index);

            var currentQuantity = parseInt(quantityInput.value);
            var unitPrice = parseFloat(unitPriceElement.innerText);

            if (operation === 'increase') {
                quantityInput.value = currentQuantity + 1;
            } else if (operation === 'decrease' && currentQuantity > 1) {
                quantityInput.value = currentQuantity - 1;
            } else if (operation === 'update') {
                // Cập nhật số lượng (gọi hàm để lưu vào cơ sở dữ liệu)
                updateQuantityInDatabase(index, currentQuantity);
            }

            // Cập nhật giá trị unitPrice và total
            unitPriceElement.innerText = unitPrice;
            totalElement.innerText = (currentQuantity * unitPrice);

            // (Optional) Gọi hàm để cập nhật tổng tiền
            updateTotalAmount();
        }
        
        function updateTotalAmount() {
            var totalAmountElement = document.getElementById('totalAmount');
            var totalAmount = 0;

            document.querySelectorAll('.totalPrice').forEach(function (element) {
                totalAmount += parseFloat(element.innerText);
            });

            totalAmountElement.innerText = totalAmount;
        }

    </script>
</head>
<body>

    <h1>Order Details</h1>

    @if (Model.OrderItems != null && Model.OrderItems.Any())
    {
        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Total Price</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.OrderItems.Count; i++)
                {
                    var item = Model.OrderItems[i];
                    <tr>
                        <td>@item.Product.ProductName</td>
                        
                        <form method="post" asp-page-handler="UpdateQuantity" asp-route-productId="@item.ProductId" asp-route-orderId="@Model.OrderId">
                        <td>
                            <button onclick="updateQuantity(@i, 'decrease')">-</button>
                            <input type="number" name="newQuantity" id="quantity_@i" value="@item.Quantity" />
                            <button onclick="updateQuantity(@i, 'increase')">+</button>
                        </td>
                        <td id="unitPrice_@i">@item.UnitPrice</td>
                        <td class="totalPrice" id="total_@i">@(item.Quantity * item.UnitPrice)</td>
                        </form>
                        <form method="post" asp-page-handler="DeleteProduct" asp-route-productId="@item.ProductId">
                        <td>
                            <input type="submit" value="Xóa" />
                        </td>
                        </form>
                        
                    </tr>
                }
            </tbody>
        </table>
        <div style="display: flex; float:right;">
            <p>Total Amount: </p>
            <p id="totalAmount">@Model.OrderItems.Sum(item => item.Quantity * item.UnitPrice)</p>
        </div>
        <form method="post" asp-page-handler="ProcessPayment" asp-route-orderId="@Model.OrderId">
            <button type="submit" class="btn btn-success">Proceed to Payment</button>
        </form>
    }
    else
    {
        <h5 style="color:red">@TempData["Message"]</h5>
        <p>This order is empty.</p>
    }

    <a asp-page="/Products/Index">Back to Product List</a>

</body>
</html>